### ISSUE TITLE
Request to update to minecraft 1.19/forge/fabric

### ISSUE THREAD

**Issue by timm-u** [lazyMods/RandomFluidCows#3]
As the title says. I would love if this mod was updated for minecraft 1.19 forge/fabric.
Bonus points if the milking system(automatic) could get put back in.

I totally understand if you don't want to do it, no pressure.. but if you get around to it.. would love to see it! :)

**Comment by lazynessmind** [comment]
Working on it. Glad you like the mod.

**Comment by marcosantos98** [comment]
Done btw.
