### ISSUE TITLE
No mobs seem to spawn in the world, summon command fails

### ISSUE THREAD

**Issue by foobazbar123** [lazyMods/RandomFluidCows#4]
Hello and good day. We just recently added this to our server and after traveling to newly generated chunks and traveling around quite a bit, no non-vanilla cows seem to spawn anywhere. I then tried the summon command shown on the mod page and I get a message of "Unable to summon entity" in game. 

On the server side, it says: "[16:05:06] [Server thread/WARN] [minecraft/EntityType]: Exception loading entity: 
java.lang.NullPointerException: null"

Let me know if you need any additional information :)

Minecraft version: 1.18.2
Forge version: forge-40.1.68

**Comment by marcosantos98** [comment]
couldn't reproduce it. sorry for the late late late response. coming back to the project. try the 1.19.2 version and tell me if this happens. sorry again for the late reply.
